services:
  flask:
    build: .
    container_name: flask-calc
    env_file:
      - .env
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx-calc
    depends_on:
      - flask
    ports:
      - "8080:80"